name:  Mejora de Documentaci贸n
description: Sugiere mejoras para la documentaci贸n
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por ayudarnos a mejorar la documentaci贸n de DeFiHub!
        
  - type: dropdown
    id: type
    attributes:
      label: Tipo de mejora
      description: 驴Qu茅 tipo de mejora en la documentaci贸n sugieres?
      options:
        - Nueva documentaci贸n
        - Actualizaci贸n de documentaci贸n existente
        - Correcci贸n de errores
        - Traducci贸n
        - Otro
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Ubicaci贸n
      description: 驴D贸nde se encuentra la documentaci贸n que necesita mejora? (URL o ruta del archivo)
      placeholder: "Ej: /docs/getting-started.md o https://defihub.com/docs/tutorial"

  - type: textarea
    id: current
    attributes:
      label: Documentaci贸n actual
      description: Si aplica, 驴qu茅 dice la documentaci贸n actual?
      placeholder: Copia el contenido actual aqu铆...

  - type: textarea
    id: suggestion
    attributes:
      label: Sugerencia de mejora
      description: 驴Qu茅 cambios sugieres?
      placeholder: Describe los cambios que te gustar铆a ver...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Informaci贸n adicional
      description: Cualquier contexto o captura de pantalla adicional que ayude a entender la mejora sugerida

  - type: checkboxes
    id: terms
    attributes:
      label: C贸digo de Conducta
      description: Al enviar este issue, aceptas seguir nuestro [C贸digo de Conducta](https://example.com)
      options:
        - label: Acepto seguir el C贸digo de Conducta de este proyecto
          required: true 